/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type AccountStatus =
  | 'active'
  | 'blocked'
  | 'deletion_requested'
  | 'restricted';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type LocaleCode = 'en' | 'ru' | 'uz-Cyrl' | 'uz-Latn';

export type OtpPurpose =
  | 'device_confirmation'
  | 'login'
  | 'phone_change'
  | 'registration';

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = 'admin' | 'candidate' | 'employer';

export interface AccountStatusHistory {
  actor_role: UserRole | null;
  actor_user_id: string | null;
  created_at: Generated<Timestamp>;
  from_status: AccountStatus | null;
  id: Generated<string>;
  reason: string | null;
  to_status: AccountStatus;
  user_id: string;
}

export interface AppMeta {
  key: string;
  updated_at: Generated<Timestamp>;
  value: string;
}

export interface DeletionRequests {
  cancelled_at: Timestamp | null;
  confirmed_at: Timestamp | null;
  id: Generated<string>;
  purge_after: Timestamp | null;
  reason: string | null;
  requested_at: Generated<Timestamp>;
  user_id: string;
}

export interface OtpCodes {
  attempts: Generated<number>;
  code_hash: string;
  consumed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  phone: string;
  purpose: OtpPurpose;
  requested_ip: string | null;
}

export interface RateLimitCounters {
  bucket: string;
  hits: Generated<number>;
  subject: string;
  window_start: Timestamp;
}

export interface Sessions {
  app_version: string | null;
  created_at: Generated<Timestamp>;
  device_fingerprint: string | null;
  device_name: string | null;
  expires_at: Timestamp;
  family_id: string;
  id: Generated<string>;
  last_used_at: Generated<Timestamp>;
  platform: string | null;
  refresh_token_hash: string;
  replaced_by_session_id: string | null;
  revoked_at: Timestamp | null;
  revoked_reason: string | null;
  user_id: string;
}

export interface UserRoles {
  granted_at: Generated<Timestamp>;
  role: UserRole;
  user_id: string;
}

export interface Users {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  last_login_at: Timestamp | null;
  locale: Generated<LocaleCode>;
  phone: string;
  status: Generated<AccountStatus>;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  account_status_history: AccountStatusHistory;
  app_meta: AppMeta;
  deletion_requests: DeletionRequests;
  otp_codes: OtpCodes;
  rate_limit_counters: RateLimitCounters;
  sessions: Sessions;
  user_roles: UserRoles;
  users: Users;
}
