import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import {
  LEGAL_LANGUAGES,
  renderLegalPages,
  serializeLegalPages,
} from './legal-pages.build';
import { LEGAL_PAGES } from './legal-pages.generated';
import {
  LegalController,
  renderPage,
  resolveLanguage,
} from './legal.controller';
import { renderMarkdown } from './markdown';

describe('renderMarkdown', () => {
  it('renders the constructs the legal documents use', () => {
    const { title, html } = renderMarkdown(
      [
        '# Title here',
        '',
        '**Effective date:** 22 September 2026  ',
        '**Contact:** a@b.uz',
        '',
        '## 1. Section',
        '',
        'A paragraph that wraps',
        'onto a second line with **bold** and a [link](https://hh.qitmir.uz/x).',
        '',
        '- first item;',
        '- second item that wraps',
        '  onto a continuation line;',
        '',
        '1. Open the app.',
        '2. Go to **Profile**.',
        '',
        '### Sub',
        '',
        'Inline `code` too.',
      ].join('\n'),
    );

    expect(title).toBe('Title here');
    expect(html).toContain('<h1>Title here</h1>');
    expect(html).toContain(
      '<strong>Effective date:</strong> 22 September 2026<br>',
    );
    expect(html).toContain('<h2>1. Section</h2>');
    expect(html).toContain('<p>A paragraph that wraps\nonto a second line');
    expect(html).toContain('<a href="https://hh.qitmir.uz/x">link</a>');
    expect(html).toContain(
      '<ul>\n<li>first item;</li>\n<li>second item that wraps onto a continuation line;</li>\n</ul>',
    );
    expect(html).toContain(
      '<ol>\n<li>Open the app.</li>\n<li>Go to <strong>Profile</strong>.</li>\n</ol>',
    );
    expect(html).toContain('<h3>Sub</h3>');
    expect(html).toContain('<code>code</code>');
  });

  it('never passes source HTML through', () => {
    // The one property a page of legal text must have: an edit to the Markdown
    // cannot inject markup, whatever it contains.
    const { html } = renderMarkdown(
      'Text <script>alert(1)</script> & "quotes"',
    );

    expect(html).not.toContain('<script>');
    expect(html).toContain('&lt;script&gt;alert(1)&lt;/script&gt;');
    expect(html).toContain('&amp; &quot;quotes&quot;');
  });

  it('emits links only for http(s) and mailto targets', () => {
    const { html } = renderMarkdown(
      '[x](javascript:alert(1)) [y](mailto:a@b.uz)',
    );

    expect(html).not.toContain('href="javascript:');
    expect(html).toContain('<a href="mailto:a@b.uz">y</a>');
  });
});

describe('the generated pages', () => {
  const docsDir = join(__dirname, '../../../docs/legal');

  it('match docs/legal/*.md — run `pnpm legal:build` after editing a policy', () => {
    // Same rule as the app repository's *.g.dart: a generated file that drifts from
    // its source ships the old text with nothing red. Regenerated in memory and
    // compared as data rather than as bytes, because `pnpm format` reflows the
    // generated module and a byte comparison would fail on the formatter's
    // whitespace, not on stale text.
    expect(LEGAL_PAGES).toEqual(renderLegalPages(docsDir));
  });

  it('are what the generator would write', () => {
    // The serializer is the one thing the object comparison above does not cover.
    const source = serializeLegalPages(renderLegalPages(docsDir));

    expect(source).toContain('GENERATED by `pnpm legal:build`');
    expect(source).toContain('export const LEGAL_PAGES: LegalPages =');
    expect(
      readFileSync(join(__dirname, 'legal-pages.generated.ts'), 'utf8'),
    ).toContain('GENERATED by `pnpm legal:build`');
  });

  it('exist in every language with a title and the other page linked', () => {
    for (const language of LEGAL_LANGUAGES) {
      expect(LEGAL_PAGES.privacy[language].title).not.toBe('');
      expect(LEGAL_PAGES.accountDelete[language].title).not.toBe('');
      // Each page links the other: Play's reviewers reach the deletion page from
      // the policy, and a user reaches the policy from the deletion page.
      expect(LEGAL_PAGES.privacy[language].html).toContain(
        'https://hh.qitmir.uz/account/delete',
      );
      expect(LEGAL_PAGES.accountDelete[language].html).toContain(
        'https://hh.qitmir.uz/privacy',
      );
    }
  });

  it('carry the contact address and no placeholder', () => {
    for (const language of LEGAL_LANGUAGES) {
      for (const page of [LEGAL_PAGES.privacy, LEGAL_PAGES.accountDelete]) {
        expect(page[language].html).toContain('@');
        expect(page[language].html).not.toMatch(/\[[A-ZА-ЯЁ][A-ZА-ЯЁ _]+\]/);
      }
    }
  });
});

describe('LegalController', () => {
  const controller = new LegalController();

  it('serves Uzbek by default and by fallback', () => {
    expect(resolveLanguage(undefined)).toBe('uz');
    expect(resolveLanguage('de')).toBe('uz');
    expect(resolveLanguage('ru')).toBe('ru');

    const page = controller.privacy(undefined);
    expect(page).toContain('<html lang="uz">');
    expect(page).toContain(LEGAL_PAGES.privacy.uz.html);
  });

  it('switches language on the same path', () => {
    const page = controller.accountDelete('en');

    expect(page).toContain('<html lang="en">');
    expect(page).toContain('<a href="/account/delete?lang=uz">');
    expect(page).toContain('<a href="/account/delete?lang=ru">');
    expect(page).toContain('<span aria-current="page">English</span>');
  });

  it('tells Cloudflare to leave the contact address alone', () => {
    // Its default email obfuscation turned the first deployment's "Contact:" line
    // into a script placeholder. The comment pair is the documented opt-out and has
    // to enclose the address; enclosing the whole document is the simplest way to
    // make that true for every page and every language.
    const page = renderPage(LEGAL_PAGES.privacy.en, 'en', 'privacy');
    const on = page.indexOf('<!--email_off-->');
    const off = page.indexOf('<!--/email_off-->');
    const address = page.indexOf('@');

    expect(on).toBeGreaterThan(-1);
    expect(address).toBeGreaterThan(on);
    expect(off).toBeGreaterThan(address);
  });

  it('loads nothing from anywhere', () => {
    // helmet's default CSP would block it, so this pins the reason the page renders
    // at all: no script, no external stylesheet, no image.
    const page = renderPage(LEGAL_PAGES.privacy.en, 'en', 'privacy');

    expect(page).not.toContain('<script');
    expect(page).not.toContain('<link');
    expect(page).not.toContain('<img');
  });
});
