import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import { renderMarkdown } from './markdown';

/**
 * Turns `docs/legal/*.md` into the TypeScript module the API serves them from.
 *
 *   pnpm legal:build
 *
 * **Why a generated module and not the files.** The runtime image carries `dist/`
 * and production dependencies and nothing else — no `docs/` — and a Markdown file
 * read at request time would be a file the container does not have. Rendering at
 * build time into a `.ts` file means the pages travel inside `dist/` like any other
 * code, need no asset copying in `nest-cli.json`, and are typed: a missing language
 * is a compile error, not a 500.
 *
 * **The generated file is committed**, and `legal-pages.spec.ts` regenerates it in
 * memory and compares — so an edit to a policy file that was not followed by
 * `pnpm legal:build` fails the suite rather than shipping the old text. The same
 * rule the app repository applies to its `*.g.dart`.
 */

/** The languages a page is served in, and the `<html lang>` each declares. */
export const LEGAL_LANGUAGES = ['uz', 'ru', 'en'] as const;
export type LegalLanguage = (typeof LEGAL_LANGUAGES)[number];

/** `docs/legal/<slug>.<suffix>.md` — the uz page is written in Latin script. */
const FILE_SUFFIX: Record<LegalLanguage, string> = {
  uz: 'uz-Latn',
  ru: 'ru',
  en: 'en',
};

export const LEGAL_DOCUMENTS = {
  privacy: 'privacy-policy',
  accountDelete: 'account-deletion',
} as const;
export type LegalDocument = keyof typeof LEGAL_DOCUMENTS;

export interface RenderedPage {
  title: string;
  html: string;
}

export type LegalPages = Record<
  LegalDocument,
  Record<LegalLanguage, RenderedPage>
>;

export function renderLegalPages(docsDir: string): LegalPages {
  const pages = {} as LegalPages;

  for (const [key, slug] of Object.entries(LEGAL_DOCUMENTS) as [
    LegalDocument,
    string,
  ][]) {
    pages[key] = {} as Record<LegalLanguage, RenderedPage>;

    for (const language of LEGAL_LANGUAGES) {
      const path = join(docsDir, `${slug}.${FILE_SUFFIX[language]}.md`);
      const rendered = renderMarkdown(readFileSync(path, 'utf8'));

      if (!rendered.title) {
        throw new Error(`${path} has no level-one heading to use as its title`);
      }

      // A placeholder the lawyer was meant to fill is not a document to publish.
      const placeholder = /\[[A-ZА-ЯЁ][A-ZА-ЯЁ _]+\]/.exec(rendered.html);

      if (placeholder) {
        throw new Error(
          `${path} still contains the placeholder ${placeholder[0]}; fill it in ` +
            `before generating the pages.`,
        );
      }

      pages[key][language] = rendered;
    }
  }

  return pages;
}

/** The module source, deterministic for a given set of inputs. */
export function serializeLegalPages(pages: LegalPages): string {
  return [
    '// GENERATED by `pnpm legal:build` from docs/legal/*.md. Do not edit; edit the',
    '// Markdown and regenerate. legal-pages.spec.ts fails when this is stale.',
    '',
    "import type { LegalPages } from './legal-pages.build';",
    '',
    `export const LEGAL_PAGES: LegalPages = ${JSON.stringify(pages, null, 2)};`,
    '',
  ].join('\n');
}
