import { Logger, Module } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';

import type { AppEnv } from '@infra/env-schema';

import { DevicesService } from './devices.service';
import { NotificationsController } from './notifications.controller';
import { NotificationsService } from './notifications.service';
import { FcmPushSender } from './push/fcm-push.sender';
import { NoopPushSender } from './push/noop-push.sender';
import { PushDispatcher } from './push/push-dispatcher.service';
import { PushSender } from './push/push-sender';

/**
 * Notifications (M9, §9.2).
 *
 * Exported, because the nine events are generated by the modules that own them - an
 * application is created in `applications`, a message in `chat` - and each calls
 * `NotificationsService.notify` after its own transaction commits. A notification is a
 * message *about* something that happened, so it must never be able to prevent the thing
 * from happening; `notify` therefore swallows and logs its own failures, which is the
 * opposite of the audit log's rule and deliberately so.
 *
 * **The push sender is chosen at boot from the configuration**, which is the seam §9.2's
 * provider plugs into: with a credential it is FCM over HTTP v1, without one it is a no-op
 * that logs rather than pretending. Everything upstream - the rows, the preferences, the
 * unread count - is identical either way, so an instance with no Firebase project is a
 * degraded instance rather than a broken one.
 */
@Module({
  controllers: [NotificationsController],
  providers: [
    NotificationsService,
    DevicesService,
    PushDispatcher,
    {
      provide: PushSender,
      inject: [ConfigService],
      useFactory: (config: ConfigService<AppEnv, true>): PushSender => {
        const credential = config.get('FCM_SERVICE_ACCOUNT_BASE64', {
          infer: true,
        });

        if (!credential) {
          // Announced at boot rather than discovered at the first notification, the way
          // the fixed OTP code announces itself.
          new Logger('NotificationsModule').warn(
            'FCM_SERVICE_ACCOUNT_BASE64 is not set: notifications are stored and read ' +
              'in-app, but no push is delivered.',
          );

          return new NoopPushSender();
        }

        return new FcmPushSender(config);
      },
    },
  ],
  exports: [NotificationsService],
})
export class NotificationsModule {}
