import type { LocaleCode, ProfileVisibility } from '@infra/db/database.types';
import { demoPhone } from '@infra/phone/demo-phone';

import type { Rgb } from './documents';

/**
 * The cast: who a tester can sign in as, and what each of them is in the middle of.
 *
 * **Declared with dictionary codes, never ids.** Every id in this product is a UUID
 * generated by `pnpm seed`, so it differs per database and a fixture holding one
 * would be unusable on the next machine. The seeder resolves each code once and fails
 * by name if a dictionary revision removes one — which is the failure you want, since
 * the alternative is a profile that silently binds nothing and renders "Unavailable
 * value" (CLAUDE.md's id/code rule, one layer down).
 *
 * **The cast is chosen to cover states, not to be a plausible sample.** Six candidates
 * is one per §2.1 category plus one deliberately unfinished; three employers cover
 * verified, awaiting verification, and individual rather than company. A seventh
 * plausible candidate would test nothing a tester cannot already reach.
 *
 * **The numbers are all `+99801…`** — see `demo-phone.ts`. They are grouped by role so
 * that a tester reading the document can tell what they are logging into before they
 * log in: `1` is a candidate, `2` an employer, `9` an administrator.
 *
 * **The codes are memorable on purpose.** They are published in
 * `docs/TEST_ACCOUNTS.md`; a shared credential nobody can remember gets written on a
 * sticky note, and there is nothing here to protect — the numbers cannot exist and
 * the accounts hold invented data.
 */

/** A ground colour per person, so the avatar in a screenshot identifies the account. */
const NAVY: Rgb = [0x14, 0x2c, 0x4a];
const TURQUOISE: Rgb = [0x1f, 0x6f, 0x8b];
const CLAY: Rgb = [0x8b, 0x4a, 0x2f];
const MOSS: Rgb = [0x3d, 0x6b, 0x35];
const PLUM: Rgb = [0x5b, 0x3a, 0x63];
const SLATE: Rgb = [0x44, 0x4f, 0x5a];

/**
 * A category field's value.
 *
 * A dictionary-backed one names **which** dictionary, rather than leaving the seeder
 * to infer it from the field's name. The first attempt inferred it from an `_ids`
 * suffix and got `specialization` wrong — it is a `dictionary_multi` over the
 * `specialization` type, not free text and not an `attribute` — which the field
 * validator caught, and would not have caught if the guess had merely picked the wrong
 * dictionary of ids.
 */
export type DemoAttribute =
  | string
  | number
  | boolean
  | { dictionary: string; codes: string[] };

export interface DemoExperience {
  employerName: string;
  roleTitle: string;
  occupationCode?: string;
  startedOn: string;
  endedOn?: string;
  isCurrent?: boolean;
  responsibilities: string;
}

export interface DemoEducation {
  levelCode: string;
  institution: string;
  specialization: string;
  graduationYear: number;
}

export interface DemoCandidate {
  key: string;
  phone: string;
  code: string;
  fullName: string;
  initials: string;
  ground: Rgb;
  locale: LocaleCode;
  headline: string;
  /** What a tester should look at on this account. Reproduced in the document. */
  purpose: string;

  dateOfBirth: string;
  genderCode: string;
  regionCode: string;
  districtCode: string;
  settlement: string;
  occupationCode: string;
  occupationLevelCode: string;
  additionalOccupationCodes: string[];
  skills: { code: string; levelCode: string }[];
  languages: { code: string; levelCode: string }[];
  employmentTypeCodes: string[];
  workFormatCodes: string[];
  salaryFrom: number;
  salaryTo: number;
  salaryPeriodCode: string;
  availableFrom: string;
  willingToRelocate: boolean;
  willingToTravel: boolean;
  /** Category fields, by code. Only the ones the candidate's category declares. */
  attributes: Record<string, DemoAttribute>;
  experience: DemoExperience[];
  education: DemoEducation[];
  visibility: ProfileVisibility;
  /** A generated CV, uploaded through the real file store. */
  wantsCv: boolean;
  wantsPhoto: boolean;
  summary: string;
}

export interface DemoVacancy {
  key: string;
  title: string;
  occupationCode: string;
  description: string;
  workerCount: number;
  regionCode: string;
  districtCode: string;
  address: string;
  employmentTypeCodes: string[];
  workFormatCodes: string[];
  shiftCodes?: string[];
  hoursPerDay?: number;
  salaryFrom: number;
  salaryTo: number;
  salaryPeriodCode: string;
  startsOn?: string;
  endsOn?: string;
  deadlineOn?: string;
  skills?: { code: string; levelCode: string; mandatory: boolean }[];
  languages?: { code: string; levelCode: string; mandatory: boolean }[];
  /** Where the vacancy should end up. `draft` is never submitted. */
  land: 'active' | 'paused' | 'under_moderation' | 'draft';
}

export interface DemoEmployer {
  key: string;
  phone: string;
  code: string;
  type: 'company' | 'individual';
  contactName: string;
  initials: string;
  ground: Rgb;
  locale: LocaleCode;
  purpose: string;

  legalName?: string;
  publicName?: string;
  industryCode?: string;
  regionCode: string;
  districtCode: string;
  address: string;
  description: string;
  contactPhone: string;
  /** `verified` runs the real admin decision; `under_review` leaves it in the queue. */
  verification: 'verified' | 'under_review';
  wantsLogo: boolean;
  vacancies: DemoVacancy[];
}

export interface DemoAdmin {
  key: string;
  phone: string;
  code: string;
  fullName: string;
  locale: LocaleCode;
  purpose: string;
}

// --- candidates ---------------------------------------------------------------

export const DEMO_CANDIDATES: DemoCandidate[] = [
  {
    key: 'c_professional',
    phone: demoPhone('1000001'),
    code: '111111',
    fullName: 'Aziza Karimova',
    initials: 'AK',
    ground: TURQUOISE,
    locale: 'uz-Latn',
    headline: 'Backend Developer',
    purpose:
      'The complete professional profile. Searchable, has a CV and a photo, ' +
      'and is mid-interview on Uzum Technologies.',
    dateOfBirth: '1997-04-18',
    genderCode: 'female',
    regionCode: 'tashkent_city',
    districtCode: 'tc_yunusobod',
    settlement: 'Yunusobod, 12-kvartal',
    occupationCode: 'backend_developer',
    occupationLevelCode: 'advanced',
    additionalOccupationCodes: ['devops_engineer'],
    skills: [
      { code: 'nodejs', levelCode: 'advanced' },
      { code: 'postgresql', levelCode: 'advanced' },
      { code: 'typescript', levelCode: 'expert' },
      { code: 'docker', levelCode: 'intermediate' },
      { code: 'git', levelCode: 'advanced' },
    ],
    languages: [
      { code: 'uzbek', levelCode: 'native' },
      { code: 'russian', levelCode: 'c1' },
      { code: 'english', levelCode: 'b2' },
    ],
    employmentTypeCodes: ['full_time'],
    workFormatCodes: ['hybrid', 'remote'],
    salaryFrom: 12_000_000,
    salaryTo: 18_000_000,
    salaryPeriodCode: 'monthly',
    availableFrom: '2026-10-01',
    willingToRelocate: false,
    willingToTravel: true,
    attributes: {
      specialization: {
        dictionary: 'specialization',
        codes: ['software_engineering', 'computer_science'],
      },
      portfolio_url: 'https://github.com/example-aziza',
    },
    experience: [
      {
        employerName: 'Uzum Market',
        roleTitle: 'Backend Developer',
        occupationCode: 'backend_developer',
        startedOn: '2023-02-01',
        isCurrent: true,
        responsibilities:
          'Order and payment services on NestJS and PostgreSQL. Owns the ' +
          'idempotency layer and the Payme integration.',
      },
      {
        employerName: 'IT Park Uzbekistan',
        roleTitle: 'Junior Developer',
        occupationCode: 'software_developer',
        startedOn: '2020-09-01',
        endedOn: '2023-01-20',
        responsibilities:
          'Internal reporting tools; moved the reporting database from ' +
          'MySQL to PostgreSQL.',
      },
    ],
    education: [
      {
        levelCode: 'bachelor',
        institution: 'Tashkent University of Information Technologies',
        specialization: 'Software Engineering',
        graduationYear: 2020,
      },
    ],
    visibility: 'searchable',
    wantsCv: true,
    wantsPhoto: true,
    summary:
      'Backend developer with six years on payment and marketplace systems. ' +
      'Comfortable owning a service end to end, from schema to deployment.',
  },
  {
    key: 'c_accountant',
    phone: demoPhone('1000002'),
    code: '111112',
    fullName: 'Jasur Toshmatov',
    initials: 'JT',
    ground: NAVY,
    locale: 'ru',
    headline: 'Accountant',
    purpose:
      'A second professional profile, in Russian, outside Tashkent. Use it to ' +
      'check region filters and the Russian interface.',
    dateOfBirth: '1989-11-02',
    genderCode: 'male',
    regionCode: 'samarkand',
    districtCode: 'sa_samarqand',
    settlement: 'Registon ko‘chasi 14',
    occupationCode: 'accountant',
    occupationLevelCode: 'expert',
    additionalOccupationCodes: ['auditor', 'economist'],
    skills: [
      { code: 'onec', levelCode: 'expert' },
      { code: 'bookkeeping', levelCode: 'expert' },
      { code: 'tax_reporting', levelCode: 'advanced' },
      { code: 'excel', levelCode: 'advanced' },
    ],
    languages: [
      { code: 'uzbek', levelCode: 'native' },
      { code: 'russian', levelCode: 'native' },
    ],
    employmentTypeCodes: ['full_time', 'part_time'],
    workFormatCodes: ['on_site'],
    salaryFrom: 7_000_000,
    salaryTo: 10_000_000,
    salaryPeriodCode: 'monthly',
    availableFrom: '2026-09-15',
    willingToRelocate: true,
    willingToTravel: false,
    attributes: {
      specialization: {
        dictionary: 'specialization',
        codes: ['accounting_audit', 'finance_banking'],
      },
    },
    experience: [
      {
        employerName: 'Samarkand Textile LLC',
        roleTitle: 'Chief Accountant',
        occupationCode: 'chief_accountant',
        startedOn: '2018-03-01',
        isCurrent: true,
        responsibilities:
          'Full accounting cycle for a 200-person plant; quarterly tax ' +
          'reporting and payroll.',
      },
    ],
    education: [
      {
        levelCode: 'master',
        institution: 'Samarkand Institute of Economics and Service',
        specialization: 'Accounting and Audit',
        graduationYear: 2012,
      },
    ],
    visibility: 'searchable',
    wantsCv: true,
    wantsPhoto: false,
    summary:
      'Chief accountant with fourteen years in manufacturing and trade. ' +
      'Handles reporting, payroll and inspections without supervision.',
  },
  {
    key: 'c_service',
    phone: demoPhone('1000003'),
    code: '111113',
    fullName: 'Nilufar Ergasheva',
    initials: 'NE',
    ground: CLAY,
    locale: 'uz-Cyrl',
    headline: 'Barista',
    purpose:
      'Service and trade category, in Uzbek Cyrillic. She has been hired on ' +
      'one vacancy, so the application history shows a terminal stage.',
    dateOfBirth: '2002-06-25',
    genderCode: 'female',
    regionCode: 'tashkent_city',
    districtCode: 'tc_chilonzor',
    settlement: 'Chilonzor, 19-kvartal',
    occupationCode: 'barista',
    occupationLevelCode: 'intermediate',
    additionalOccupationCodes: ['waiter', 'cashier'],
    skills: [
      { code: 'coffee_making', levelCode: 'advanced' },
      { code: 'customer_service', levelCode: 'advanced' },
      { code: 'cash_register', levelCode: 'intermediate' },
      { code: 'food_hygiene', levelCode: 'intermediate' },
    ],
    languages: [
      { code: 'uzbek', levelCode: 'native' },
      { code: 'russian', levelCode: 'b1' },
      { code: 'english', levelCode: 'a2' },
    ],
    employmentTypeCodes: ['full_time', 'shift'],
    workFormatCodes: ['on_site'],
    salaryFrom: 3_500_000,
    salaryTo: 5_000_000,
    salaryPeriodCode: 'monthly',
    availableFrom: '2026-09-01',
    willingToRelocate: false,
    willingToTravel: false,
    attributes: {
      readiness_ids: { dictionary: 'attribute', codes: ['physical_work'] },
    },
    experience: [
      {
        employerName: 'Chorsu Coffee',
        roleTitle: 'Barista',
        occupationCode: 'barista',
        startedOn: '2024-05-01',
        isCurrent: true,
        responsibilities:
          'Espresso bar, morning shift; trains new staff on the machine.',
      },
      {
        employerName: 'Bon! Bakery',
        roleTitle: 'Cashier',
        occupationCode: 'cashier',
        startedOn: '2022-08-01',
        endedOn: '2024-04-15',
        responsibilities: 'Till, stock counts and end-of-day reconciliation.',
      },
    ],
    education: [
      {
        levelCode: 'secondary_special',
        institution: 'Tashkent College of Food Technology',
        specialization: 'Catering',
        graduationYear: 2021,
      },
    ],
    visibility: 'searchable',
    wantsCv: false,
    wantsPhoto: true,
    summary:
      'Barista with four years behind an espresso bar, used to a full ' +
      'morning rush and to training the person next to her.',
  },
  {
    key: 'c_industrial',
    phone: demoPhone('1000004'),
    code: '111114',
    fullName: 'Bekzod Rahimov',
    initials: 'BR',
    ground: SLATE,
    locale: 'uz-Latn',
    headline: 'Welder',
    purpose:
      'Physical and industrial category: licences, tools and safety fields ' +
      'that no other category shows. Carries a certificate as well as a CV.',
    dateOfBirth: '1994-02-11',
    genderCode: 'male',
    regionCode: 'andijan',
    districtCode: 'an_asaka',
    settlement: 'Asaka, Sanoat ko‘chasi',
    occupationCode: 'welder',
    occupationLevelCode: 'advanced',
    additionalOccupationCodes: ['assembler'],
    skills: [
      { code: 'welding_arc', levelCode: 'expert' },
      { code: 'welding_gas', levelCode: 'advanced' },
      { code: 'blueprint_reading', levelCode: 'intermediate' },
      { code: 'safety_rules', levelCode: 'advanced' },
    ],
    languages: [
      { code: 'uzbek', levelCode: 'native' },
      { code: 'russian', levelCode: 'b1' },
    ],
    employmentTypeCodes: ['full_time', 'shift'],
    workFormatCodes: ['on_site'],
    salaryFrom: 6_000_000,
    salaryTo: 9_000_000,
    salaryPeriodCode: 'monthly',
    availableFrom: '2026-09-08',
    willingToRelocate: true,
    willingToTravel: true,
    attributes: {
      licence_ids: {
        dictionary: 'attribute',
        codes: ['licence_b', 'licence_c'],
      },
      transport_ids: { dictionary: 'attribute', codes: ['own_car'] },
      tool_ids: {
        dictionary: 'attribute',
        codes: ['hand_tools', 'power_tools', 'safety_equipment'],
      },
      readiness_ids: {
        dictionary: 'attribute',
        codes: ['physical_work', 'field_travel', 'crew_work'],
      },
      crew_size: 4,
    },
    experience: [
      {
        employerName: 'UzAuto Motors',
        roleTitle: 'Welder, 5th grade',
        occupationCode: 'welder',
        startedOn: '2019-04-01',
        isCurrent: true,
        responsibilities:
          'Body-shop welding on the assembly line; leads a crew of four on ' +
          'the night shift.',
      },
    ],
    education: [
      {
        levelCode: 'secondary_special',
        institution: 'Asaka Technical College',
        specialization: 'Welding Technology',
        graduationYear: 2013,
      },
    ],
    visibility: 'searchable',
    wantsCv: true,
    wantsPhoto: false,
    summary:
      'Welder with a 5th-grade certificate and seven years on an automotive ' +
      'line. Leads a four-person crew and holds B and C licences.',
  },
  {
    key: 'c_seasonal',
    phone: demoPhone('1000005'),
    code: '111115',
    fullName: 'Sardor Yo‘ldoshev',
    initials: 'SY',
    ground: MOSS,
    locale: 'uz-Latn',
    headline: 'Tractor Driver',
    purpose:
      'Seasonal and agricultural category, where the form asks for dates and ' +
      'crew readiness. Has one application still at the first stage.',
    dateOfBirth: '1991-08-30',
    genderCode: 'male',
    regionCode: 'fergana',
    districtCode: 'fa_quva',
    settlement: 'Quva tumani, Yangiobod QFY',
    occupationCode: 'tractor_driver',
    occupationLevelCode: 'advanced',
    additionalOccupationCodes: ['combine_operator', 'field_worker'],
    skills: [
      { code: 'tractor_operation', levelCode: 'expert' },
      { code: 'harvesting', levelCode: 'advanced' },
      { code: 'irrigation', levelCode: 'intermediate' },
      { code: 'equipment_maintenance', levelCode: 'intermediate' },
    ],
    languages: [{ code: 'uzbek', levelCode: 'native' }],
    employmentTypeCodes: ['seasonal', 'temporary'],
    workFormatCodes: ['field'],
    salaryFrom: 250_000,
    salaryTo: 400_000,
    salaryPeriodCode: 'daily',
    availableFrom: '2026-09-05',
    willingToRelocate: true,
    willingToTravel: true,
    attributes: {
      licence_ids: { dictionary: 'attribute', codes: ['licence_c'] },
      transport_ids: { dictionary: 'attribute', codes: ['own_motorcycle'] },
      readiness_ids: {
        dictionary: 'attribute',
        codes: ['physical_work', 'field_travel', 'crew_work', 'relocation'],
      },
      crew_size: 8,
    },
    experience: [
      {
        employerName: 'Quva Agro Klaster',
        roleTitle: 'Tractor Driver',
        occupationCode: 'tractor_driver',
        startedOn: '2016-03-01',
        isCurrent: true,
        responsibilities:
          'Ploughing, sowing and harvest across 300 hectares; keeps two ' +
          'tractors running through the season.',
      },
    ],
    education: [
      {
        levelCode: 'secondary',
        institution: 'Quva School №12',
        specialization: 'General secondary',
        graduationYear: 2008,
      },
    ],
    visibility: 'searchable',
    wantsCv: false,
    wantsPhoto: false,
    summary:
      'Tractor and combine driver, ten seasons in the Fergana valley. Brings ' +
      'a crew of eight and travels for the harvest.',
  },
  {
    key: 'c_incomplete',
    phone: demoPhone('1000006'),
    code: '111116',
    fullName: 'Malika Usmonova',
    initials: 'MU',
    ground: PLUM,
    locale: 'uz-Latn',
    headline: 'Shift worker',
    purpose:
      'Deliberately unfinished and hidden from search. This is the account ' +
      'for testing the completeness card, the BR-02 gate and the empty states — ' +
      'she must NOT appear in an employer’s candidate search.',
    dateOfBirth: '2004-01-19',
    genderCode: 'female',
    regionCode: 'tashkent_city',
    districtCode: 'tc_sergeli',
    settlement: 'Sergeli, 7-kvartal',
    occupationCode: 'shift_worker',
    occupationLevelCode: 'basic',
    additionalOccupationCodes: [],
    // Everything below this line is deliberately thin: no skills, one language,
    // no salary expectation, no history. That is what makes the percentage low.
    skills: [],
    languages: [{ code: 'uzbek', levelCode: 'native' }],
    employmentTypeCodes: [],
    workFormatCodes: [],
    salaryFrom: 0,
    salaryTo: 0,
    salaryPeriodCode: 'daily',
    availableFrom: '',
    willingToRelocate: false,
    willingToTravel: false,
    attributes: {},
    experience: [],
    education: [],
    visibility: 'hidden',
    wantsCv: false,
    wantsPhoto: false,
    summary: '',
  },
];

// --- employers ----------------------------------------------------------------

export const DEMO_EMPLOYERS: DemoEmployer[] = [
  {
    key: 'e_verified',
    phone: demoPhone('2000001'),
    code: '222221',
    type: 'company',
    contactName: 'Dilshod Nazarov',
    initials: 'UT',
    ground: NAVY,
    locale: 'uz-Latn',
    purpose:
      'The main employer account. Verified, has a logo, a Coin balance, three ' +
      'vacancies in three different states and applications at four stages.',
    legalName: 'ООО «Uzum Technologies»',
    publicName: 'Uzum Technologies',
    industryCode: 'it_software',
    regionCode: 'tashkent_city',
    districtCode: 'tc_mirzo_ulugbek',
    address: 'Amir Temur shoh ko‘chasi 108, Tashkent',
    description:
      'Product engineering for the Uzum group: marketplace, fintech and ' +
      'logistics. Around 400 engineers in Tashkent.',
    contactPhone: '+998712000001',
    verification: 'verified',
    wantsLogo: true,
    vacancies: [
      {
        key: 'v_backend',
        title: 'Backend Developer (Node.js)',
        occupationCode: 'backend_developer',
        description:
          'We are looking for a backend developer for the payments team. ' +
          'You will work on NestJS services backed by PostgreSQL, own the ' +
          'integrations with Payme and CLICK, and take part in on-call. ' +
          'Hybrid: three days in the Tashkent office, two remote.',
        workerCount: 2,
        regionCode: 'tashkent_city',
        districtCode: 'tc_mirzo_ulugbek',
        address: 'Amir Temur shoh ko‘chasi 108',
        employmentTypeCodes: ['full_time'],
        workFormatCodes: ['hybrid'],
        salaryFrom: 13_000_000,
        salaryTo: 20_000_000,
        salaryPeriodCode: 'monthly',
        deadlineOn: '2026-11-30',
        skills: [
          { code: 'nodejs', levelCode: 'advanced', mandatory: true },
          { code: 'postgresql', levelCode: 'intermediate', mandatory: true },
          { code: 'docker', levelCode: 'basic', mandatory: false },
        ],
        languages: [
          { code: 'uzbek', levelCode: 'b2', mandatory: true },
          { code: 'english', levelCode: 'b1', mandatory: false },
        ],
        land: 'active',
      },
      {
        key: 'v_qa',
        title: 'QA Engineer (mobile)',
        occupationCode: 'qa_engineer',
        description:
          'Manual and automated testing of an Android application. You will ' +
          'own the release checklist, write regression cases and reproduce ' +
          'field reports. Paused while the team is being reorganised.',
        workerCount: 1,
        regionCode: 'tashkent_city',
        districtCode: 'tc_mirzo_ulugbek',
        address: 'Amir Temur shoh ko‘chasi 108',
        employmentTypeCodes: ['full_time'],
        workFormatCodes: ['on_site'],
        salaryFrom: 9_000_000,
        salaryTo: 13_000_000,
        salaryPeriodCode: 'monthly',
        skills: [{ code: 'testing', levelCode: 'advanced', mandatory: true }],
        land: 'paused',
      },
      {
        key: 'v_analyst',
        title: 'Data Analyst',
        occupationCode: 'data_analyst',
        description:
          'Analytics for the marketplace: cohort reporting, funnel analysis ' +
          'and dashboards for the commercial team. SQL every day, Power BI ' +
          'for delivery. This vacancy is waiting for moderation on purpose.',
        workerCount: 1,
        regionCode: 'tashkent_city',
        districtCode: 'tc_mirzo_ulugbek',
        address: 'Amir Temur shoh ko‘chasi 108',
        employmentTypeCodes: ['full_time'],
        workFormatCodes: ['hybrid'],
        salaryFrom: 10_000_000,
        salaryTo: 15_000_000,
        salaryPeriodCode: 'monthly',
        skills: [
          { code: 'sql', levelCode: 'advanced', mandatory: true },
          { code: 'power_bi', levelCode: 'intermediate', mandatory: false },
        ],
        land: 'under_moderation',
      },
    ],
  },
  {
    key: 'e_pending',
    phone: demoPhone('2000002'),
    code: '222222',
    type: 'company',
    contactName: 'Kamola Yusupova',
    initials: 'SR',
    ground: CLAY,
    locale: 'ru',
    purpose:
      'Waiting for verification, with its documents already submitted. This is ' +
      'what puts a row in the administrator’s verification queue — and the ' +
      'account to use for checking what an unverified employer cannot do.',
    legalName: 'ООО «Silk Road Logistics»',
    publicName: 'Silk Road Logistics',
    industryCode: 'transport_logistics',
    regionCode: 'tashkent_region',
    districtCode: 'tr_zangiota',
    address: 'Zangiota tumani, Logistika markazi 4',
    description:
      'Freight forwarding and warehousing between Tashkent, Almaty and ' +
      'Urumqi. Twelve trucks and a 6 000 m² warehouse.',
    contactPhone: '+998712000002',
    verification: 'under_review',
    wantsLogo: true,
    vacancies: [],
  },
  {
    key: 'e_individual',
    phone: demoPhone('2000003'),
    code: '222223',
    type: 'individual',
    contactName: 'Otabek Sattorov',
    initials: 'OS',
    ground: MOSS,
    locale: 'uz-Latn',
    purpose:
      'An individual employer rather than a company — a different profile form ' +
      'and different required evidence. Verified, with one active seasonal ' +
      'vacancy that has two applicants.',
    regionCode: 'fergana',
    districtCode: 'fa_quva',
    address: 'Quva tumani, Yangiobod QFY',
    description:
      'Family farm growing apricots and grapes on 40 hectares. Hires crews ' +
      'for planting and for the harvest.',
    contactPhone: '+998912000003',
    verification: 'verified',
    wantsLogo: false,
    vacancies: [
      {
        key: 'v_harvest',
        title: 'Harvest crew — apricot season',
        occupationCode: 'harvest_worker',
        description:
          'Crew work for the apricot harvest: picking, sorting and loading. ' +
          'Meals and transport from Quva centre are provided. Paid daily, in ' +
          'cash, at the end of each working day.',
        workerCount: 15,
        regionCode: 'fergana',
        districtCode: 'fa_quva',
        address: 'Yangiobod QFY, 3-brigada',
        employmentTypeCodes: ['seasonal'],
        workFormatCodes: ['field'],
        hoursPerDay: 8,
        salaryFrom: 200_000,
        salaryTo: 300_000,
        salaryPeriodCode: 'daily',
        startsOn: '2026-09-10',
        endsOn: '2026-10-25',
        deadlineOn: '2026-09-08',
        land: 'active',
      },
    ],
  },
];

// --- administrator --------------------------------------------------------------

export const DEMO_ADMIN: DemoAdmin = {
  key: 'a_admin',
  phone: demoPhone('9000001'),
  code: '999999',
  fullName: 'Shahzod Alimov (demo admin)',
  locale: 'uz-Latn',
  purpose:
    'The administrator. Its queues are not empty on purpose: one vacancy is ' +
    'waiting for moderation, one employer for verification, and one complaint ' +
    'for review.',
};

/** Every seeded account, in the order the document lists them. */
export function demoRoster(): {
  phone: string;
  code: string;
  label: string;
  role: string;
  purpose: string;
}[] {
  return [
    ...DEMO_CANDIDATES.map((c) => ({
      phone: c.phone,
      code: c.code,
      label: `${c.fullName} — ${c.headline}`,
      role: 'candidate',
      purpose: c.purpose,
    })),
    ...DEMO_EMPLOYERS.map((e) => ({
      phone: e.phone,
      code: e.code,
      label: `${e.publicName ?? e.contactName} — ${e.contactName}`,
      role: 'employer',
      purpose: e.purpose,
    })),
    {
      phone: DEMO_ADMIN.phone,
      code: DEMO_ADMIN.code,
      label: DEMO_ADMIN.fullName,
      role: 'admin',
      purpose: DEMO_ADMIN.purpose,
    },
  ];
}
